In [265]:
# Q

In [266]:
str = ["e","x","a","m"]
print(str)
str.reverse()
print(str)

['e', 'x', 'a', 'm']
['m', 'a', 'x', 'e']


In [267]:
# Q

In [281]:
s = ["d","a","d"]
print(s)
s.ispalindrome()
print(s)

['d', 'a', 'd']


AttributeError: 'list' object has no attribute 'ispalindrome'

In [282]:
p = "level"
r = ""
for i in p:
    r = i + r
if (p == r):
    print("Yes")
else:
    print("No")

Yes


In [283]:
# Q

In [284]:
import numpy as np

In [285]:
data = np.arange(1,13).reshape(3,4)
print(data)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [286]:
# Q

In [287]:
a = ['p','y','t','h','o','n']
print(a)
def sample(a):
    b =[]
    le = len(a)-1
    while(le>=0):
        b.append(a[le])
        le = le-1
    return b

['p', 'y', 't', 'h', 'o', 'n']


In [288]:
sample(a)

['n', 'o', 'h', 't', 'y', 'p']

In [289]:
# Q

In [290]:
def cube(x):
    return x**3

In [291]:
cube(2)

8

In [292]:
list1 =[2,3,4]
list2 =[3,3,3]
list(map(cube,(list1),(list2)))

TypeError: 'list' object is not callable